[build]
builder = "RAILPACK"
buildCommand = "echo 'No build needed - Bun runs TypeScript directly'"

[deploy]
startCommand = "bun run start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.preDeploy]]
command = "bun run db:migrate"
