[build]
builder = "RAILPACK"
buildCommand = "echo 'No build needed - Bun runs TypeScript directly'"
watchPatterns = ["packages/platform-api/**", "packages/sdks/nodejs/**"]

[deploy]
startCommand = "cd packages/platform-api && bun run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
