#!/bin/bash
set -e

GRAFANA_URL="http://grafana:3000"
GRAFANA_USER="admin"
GRAFANA_PASSWORD="admin123"
SERVICE_ACCOUNT_NAME="folder-provisioner"
TOKEN_NAME="webhook-service-token"
TOKEN_FILE="/shared/grafana-token.txt"
ENV_FILE="/shared/.env"

echo "Waiting for Grafana to be ready..."
until curl -s ${GRAFANA_URL}/api/health > /dev/null 2>&1; do
  echo "Grafana not ready, waiting..."
  sleep 5
done

echo "Grafana is ready! Creating service account and token..."

# Check if token file already exists
if [ -f "$TOKEN_FILE" ]; then
  echo "Token file already exists, skipping creation"
  exit 0
fi

# Try to create service account or get existing one
echo "Creating or finding service account: $SERVICE_ACCOUNT_NAME"
SERVICE_ACCOUNT_RESPONSE=$(curl -s -X POST \
  -H "Content-Type: application/json" \
  -u "${GRAFANA_USER}:${GRAFANA_PASSWORD}" \
  -d "{\"name\":\"${SERVICE_ACCOUNT_NAME}\",\"role\":\"Admin\"}" \
  ${GRAFANA_URL}/api/serviceaccounts)

# Extract service account ID from creation response
SERVICE_ACCOUNT_ID=$(echo $SERVICE_ACCOUNT_RESPONSE | grep -o '"id":[0-9]*' | cut -d: -f2)

# If creation failed (e.g., already exists), search for existing service account
if [ -z "$SERVICE_ACCOUNT_ID" ]; then
  echo "Service account might already exist, searching for it..."
  SEARCH_RESPONSE=$(curl -s -X GET \
    -H "Content-Type: application/json" \
    -u "${GRAFANA_USER}:${GRAFANA_PASSWORD}" \
    "${GRAFANA_URL}/api/serviceaccounts/search?query=${SERVICE_ACCOUNT_NAME}")
  
  SERVICE_ACCOUNT_ID=$(echo $SEARCH_RESPONSE | grep -o '"id":[0-9]*' | head -1 | cut -d: -f2)
fi

if [ -z "$SERVICE_ACCOUNT_ID" ]; then
  echo "Failed to create or find service account. Create response: $SERVICE_ACCOUNT_RESPONSE"
  exit 1
fi

echo "Using service account with ID: $SERVICE_ACCOUNT_ID"

# Create token for service account
echo "Creating token: $TOKEN_NAME"
TOKEN_RESPONSE=$(curl -s -X POST \
  -H "Content-Type: application/json" \
  -u "${GRAFANA_USER}:${GRAFANA_PASSWORD}" \
  -d "{\"name\":\"${TOKEN_NAME}\"}" \
  ${GRAFANA_URL}/api/serviceaccounts/${SERVICE_ACCOUNT_ID}/tokens)

# Extract token
TOKEN=$(echo $TOKEN_RESPONSE | grep -o '"key":"[^"]*"' | cut -d'"' -f4)

if [ -z "$TOKEN" ]; then
  echo "Failed to create token. Response: $TOKEN_RESPONSE"
  exit 1
fi

# Save token to shared volume
echo "$TOKEN" > "$TOKEN_FILE"
echo "Token saved to $TOKEN_FILE"

# Create .env file with the token
cat > "$ENV_FILE" << EOF
# Auto-generated Grafana API Configuration
GRAFANA_API_TOKEN=${TOKEN}
GRAFANA_API_URL=http://grafana:3000
WEBHOOK_PORT=3001

# This file was automatically generated by the init script
# Token created: $(date)
EOF

echo ".env file created at $ENV_FILE"
echo "Grafana initialization complete!"