# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

builds:
  - id: veil
    no_main_check: true
    dir: ./packages/caddy
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: amd64
    binary: veil
    hooks:
      pre: make build
    flags:
      - -tags=netgo
    ldflags:
      - -s -w
      - -linkmode=external
      - -X main.version={{.Version}}
    overrides:
      - goos: darwin
        goarch: amd64
        env:
          - CC=o64-clang
          - CXX=o64-clang++
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
          - CXX=oa64-clang++
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++

nfpms:
  - id: packages
    package_name: veil
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: TheFlywheel
    homepage: https://github.com/try-veil/veil
    maintainer: Yash Mittal <yash@techsavvyash.dev>
    description: Veil - An opionated Caddy extension to sell, monitor, and manage your APIs
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - git
      - xcaddy
    recommends:
      - caddy

archives:
  - formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - README*
      - LICENSE*

brews:
  - name: veil
    repository:
      owner: try-veil
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/try-veil/veil"
    description: "Veil - An opinionated, fully featured, modular observability stack for APIs. Allows you to sell, monitor, authenticate your APIs."
    license: "MIT"
    test: |
      system "#{bin}/veil version"
    install: |
      bin.install "veil"

aurs:
  - name: veil-bin
    homepage: "https://github.com/try-veil/veil"
    description: "Veil - An opinionated, fully featured, modular observability stack for APIs. Allows you to sell, monitor, authenticate your APIs."
    maintainers:
      - "Yash Mittal <yash@techsavvyash.dev>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/veil-bin.git"
    package: |-
      # bin
      install -Dm755 "./veil" "${pkgdir}/usr/bin/veil"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/veil/LICENSE"

publishers:
  - name: cloudsmith
    ids:
      - packages
    env:
      - CLOUDSMITH_API_KEY={{ .Env.CLOUDSMITH_API_KEY }}
    cmd: >-
      bash -c 'for file in dist/*.deb; do
      if [ -f "$file" ]; then
      curl -f -X POST "https://upload.cloudsmith.io/theflywheel/veil/debian/main/"
      -H "X-Api-Key: $CLOUDSMITH_API_KEY"
      -F "package=@$file"; fi; done;
      for file in dist/*.rpm; do
      if [ -f "$file" ]; then
      curl -f -X POST "https://upload.cloudsmith.io/theflywheel/veil/rpm/main/"
      -H "X-Api-Key: $CLOUDSMITH_API_KEY"
      -F "package=@$file"; fi; done'

release:
  github:
    owner: try-veil
    name: veil
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Installation
    
    ### Homebrew (macOS/Linux)
    ```bash
    brew install try-veil/tap/veil
    ```
    
    ### Arch Linux (AUR)
    ```bash
    yay -S veil-bin
    ```
    
    ### Manual Installation
    Download the appropriate package for your system from the assets below.
  footer: |
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser) on behalf of TheFlywheel.

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch
