[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "/usr/bin/veil run --config /etc/caddy/Caddyfile"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
