openapi: 3.0.0
info:
  title: Veil API Management
  description: API management and subscription validation service for Caddy
  version: 1.0.0
  contact:
    name: Veil Support
    url: https://github.com/techsavvyash/veil

servers:
  - url: http://localhost:2020
    description: Local development server

paths:
  /veil/api/onboard:
    post:
      summary: Onboard a new API
      description: Register a new API with Veil for subscription-based access control
      tags:
        - API Management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/APIOnboardRequest"
      responses:
        "200":
          description: API successfully onboarded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIOnboardResponse"
        "400":
          description: Invalid request body or missing required fields
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    APIOnboardRequest:
      type: object
      required:
        - path
        - upstream
        - required_subscription
        - methods
      properties:
        path:
          type: string
          description: The API path pattern to match
          example: /api/v1/products/*
        upstream:
          type: string
          description: The upstream service URL
          example: http://localhost:8081
        required_subscription:
          type: string
          description: Required subscription level for access
          example: premium
        methods:
          type: array
          description: Allowed HTTP methods
          items:
            type: string
            enum: [GET, POST, PUT, DELETE, PATCH]
          example: [GET, POST]
        required_headers:
          type: array
          description: Required request headers
          items:
            type: string
          example: [X-API-Key, X-Request-ID]
        parameters:
          type: array
          description: Required request parameters
          items:
            $ref: "#/components/schemas/Parameter"
        api_keys:
          type: array
          description: List of valid API keys
          items:
            $ref: "#/components/schemas/APIKey"

    Parameter:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
          description: Parameter name
          example: category
        type:
          type: string
          enum: [query, header, path]
          description: Parameter type
          example: query
        required:
          type: boolean
          description: Whether the parameter is required
          example: true

    APIKey:
      type: object
      required:
        - name
        - is_active
      properties:
        name:
          type: string
          description: API key value
          example: test-key-123
        is_active:
          type: boolean
          description: Whether the API key is active
          example: true

    APIOnboardResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: API onboarded successfully
        api:
          $ref: "#/components/schemas/APIConfig"

    APIConfig:
      type: object
      properties:
        path:
          type: string
          example: /api/v1/products/*
        upstream:
          type: string
          example: http://localhost:8081
        required_subscription:
          type: string
          example: premium
        methods:
          type: array
          items:
            type: string
          example: [GET, POST]
        required_headers:
          type: array
          items:
            type: string
          example: [X-API-Key, X-Request-ID]
        parameters:
          type: array
          items:
            $ref: "#/components/schemas/Parameter"
        api_keys:
          type: array
          items:
            $ref: "#/components/schemas/APIKey"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: Invalid request body

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    SubscriptionAuth:
      type: apiKey
      in: header
      name: X-Subscription-Key

security:
  - ApiKeyAuth: []
    SubscriptionAuth: []
